# Generated by Django 4.2.3 on 2023-07-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='nome',
        ),
    ]
