# Generated by Django 4.2.3 on 2023-07-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_conta_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='valor',
            new_name='valor_planejamento',
        ),
    ]
